---
  environment: production
  chdir: /var/www
  pid: /var/www/config/thin/tmp/thin.pid
  rackup: /var/www/config/thin/config.ru
  log: /var/www/config/thin/log/thin.log
  daemonize: true
  port: 8080
